apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
    env: production
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
