apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nextgen-telco-dev

namespace: development

commonLabels:
  environment: dev
  project: nextgen-telco

resources:
  - frontend/kustomization.yaml
  - user-service/kustomization.yaml
  - order-service/kustomization.yaml
